name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: 3.2
          - ruby-version: 3.1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Build and test
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
          BUNDLER: ${{ matrix.bundler-version }}
        run: |
          gem uninstall bundler
          gem install bundler -v ${BUNDLER:-2.1.4}
          bundle install --jobs 4 --retry 3
          bundle exec rake
